# Pre-commit hooks for automated quality checks
repos:
    # Ruff for linting and formatting
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.8.0
      hooks:
          - id: ruff
            args: [--fix]
          - id: ruff-format

    # Type checking with mypy
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.13.0
      hooks:
          - id: mypy
            files: ^src/
            args: [--ignore-missing-imports, --explicit-package-bases]

    # General code quality
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: check-merge-conflict
          - id: debug-statements

    # Security scanning
    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.10
      hooks:
          - id: bandit
            args: [-r]
            exclude: ^tests/
